---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# rteachtools

<!-- badges: start -->
<!-- badges: end -->

The package website can be found at  https://charlotte-ngs.github.io/rteachtools/

The goal of rteachtools is to provide basic functionality to help in teaching courses


## Installation

You can install the released version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("charlotte-ngs/rteachtools")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example, eval=FALSE}
library(rteachtools)
## creating a new exercise document
rteachtools::create_exercise(ps_ex_path    = "ex/gel_ex01/gel_ex01.Rmd",
                             pn_nr_problem = 2,
                             pl_data       = list(course_name    = "Genetic Evaluation",
                                                  exercise_count = 1,
                                                  creation_date  = format(Sys.Date(), "%Y-%m-%d"),
                                                  author         = "Peter von Rohr"))

```


```{r, echo=FALSE, results='asis'}
cat("\n---\n\n _Latest Changes: ", format(Sys.time(), "%Y-%m-%d, %H:%M:%S"),  "(", Sys.info()[["user"]], ")_")
```

